dbt-bq:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: cogent-range-355320
      dataset: spotify
      threads: 4
      keyfile: /secrets/dbt-service-keyfile
      timeout_seconds: 300
      priority: interactive
      retries: 1